apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shipping
  template:
    metadata:
      labels:
        app: shipping
    spec:
      containers:
        - name: shipping
          image: europe-west1-docker.pkg.dev/planar-method-462122-s6/cloud-run-source-deploy/asid_shipping_microservice:latest
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://34.38.20.72:3306/shipping_db
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: qd&ELDsZYqo*V>C.
            - name: SPRING_RABBITMQ_HOST
              value: dog.lmq.cloudamqp.com
            - name: SPRING_RABBITMQ_PORT
              value: "5672"
            - name: SPRING_RABBITMQ_USERNAME
              value: qscwboat
            - name: SPRING_RABBITMQ_PASSWORD
              value: mz9JhbgM2SEwXIVuNhEb3qnyvBAIXueK
            - name: SPRING_RABBITMQ_VIRTUALHOST
              value: qscwboat
